// data.js - Constantes y datos globales de la aplicacion


let SEDES = [];
let SEDES_CHECKIN = [];
let SEDE_ZONAS = {};

// El listado de personal (nombre, cedula, whatsapp, correo, jefe) vive solo en
// el servidor (Code.gs -> PERSONAL_) para no exponer datos personales ni
// credenciales de acceso (cedula) a cualquiera que abra el sitio.
// El login ahora se valida contra el backend (ver loginTecnico() en js/app.js).


function inicializarDatosEquipos() {
    const sedesSet = new Set();
    const sedeZonasMap = {};

    for (const sede in ZONA_EQUIPOS) {
        sedesSet.add(sede);
        if (!sedeZonasMap[sede]) sedeZonasMap[sede] = [];
        for (const zona in ZONA_EQUIPOS[sede]) {
            const zonaUp = zona.toUpperCase();
            if (sedeZonasMap[sede].indexOf(zonaUp) === -1) sedeZonasMap[sede].push(zonaUp);
        }
    }

    SEDES = Array.from(sedesSet);
    if (SEDES.indexOf("EVENTO") === -1) SEDES.push("EVENTO");
    SEDES_CHECKIN = SEDES.filter(function(s) { return s !== "EVENTO"; });

    SEDE_ZONAS = {};
    for (const sede in sedeZonasMap) {
        const zonasArr = sedeZonasMap[sede].slice().sort();
        if (sede !== "EVENTO" && zonasArr.indexOf("EXTERIOR") === -1) zonasArr.push("EXTERIOR");
        SEDE_ZONAS[sede] = zonasArr;
    }
}

function getAveriaZonas(sede) {
    if (sede === "EVENTO") return [];
    var zonas = (SEDE_ZONAS[sede] || []).filter(function(z) { return z.toUpperCase().indexOf("SEMANERO") !== 0; });
    if (zonas.indexOf("EXTERIOR") === -1) zonas.push("EXTERIOR");
    return zonas;
}

const ZONA_EQUIPOS = {
    "RUICES": {
        "PB": [
            "CAVA CUARTO DE CONGELACION 1",
            "CAVA CUARTO DE CONGELACION 2",
            "CAVA CUARTO DE CONGELACION 3",
            "CAVA CUARTO DE CONSERVACION 1",
            "AIRE ACONDICIONADO 5 TON FAN COIL 1",
            "AIRE ACONDICIONADO 5 TON FAN COIL 2",
            "MESON REFRIGERADO 2 PTA 1 URSEL",
            "MESON REFRIGERADO 3 PTA 1 URSEL",
            "ARMARIO REFRIGERADO URSEL 1",
            "NEVERA EXHIBIDORA",
            "SISTEMA HIDRONEUMATICO",
            "TANQUES DE AGUA DE 1000LTS (8 UN)",
            "FILTRO DESBARRADOR",
            "HORNO RATIONAL A GAS 220 V PH2",
            "PELA PAPAS 220 V",
            "REBANADORA # 1",
            "EMPACADORA AL VACIO # 1 VAC MASTER",
            "EMPACADORA AL VACIO # 2 VAMA",
            "ROBOCOP",
            "FREIDORA # 1",
            "COCINA TURCA # 1",
            "MOTOR DE INYECCION DE AIRE # 1",
            "BATIDORA KITCHENAID",
            "ENFRIADOR DE AGUA # 1",
            "FILTRO DE CARBON ACTIVADO",
            "ELEVADOR DE CARGA",
            "TABLEROS ELECTRICOS",
            "FUMIGACION",
            "EXTINTORES",
            "PINTURA EXTERNA",
            "PINTURA INTERNA",
            "TABLEROS",
            "LAMPARAS",
            "ESCRITORIOS",
        ],
        "PISO 1": [
            "CAVA CUARTO DE CONSERVACION 2",
            "AIRE ACONDICIONADO 5 TON FAN COIL 3",
            "AIRE ACONDICIONADO 18000 BTU ENTRADAS",
            "AIRE ACONDICIONADO 12000 BTU PANADERIA",
            "AIRE ACONDICIONADO 18000 BTU COMEDOR",
            "MESON REFRIGERADO 2 PTA BALSAM 1 / PANTRY",
            "MESON REFRIGERADO 2 PTA BALSAM 2 / PANTRY",
            "MESON REFRIGERADO DE GAVETA BALSAM 1 / PRINCIPAL",
            "MESON REFRIGERADO DE GAVETA BALSAM 2 / PRINCIPAL",
            "MESON REFRIGERADO DE GAVETA COMIDA EN FAMILIA",
            "ARMARIO REFRIGERADO URSEL 2",
            "ABATIDOR",
            "CORTINA DE AIRE 150 CM, 220V",
            "HORNO RATIONAL TRIFASICO 220V PH3",
            "HORNO ELECTRICO BALSAM 110 V-PH1 # 1",
            "HORNO ELECTRICO BALSAM 110 V-PH1 # 2",
            "REBANADORA # 2",
            "REBANADORA # 3 NUEVA",
            "FREIDORA # 2",
            "FREIDORA # 3",
            "COCINA TURCA # 2",
            "COCINA IBOIA # 3",
            "TOPE FRANCES A GAS 1",
            "TOPE FRANCES A GAS 2",
            "PLANCHA A GAS",
            "SARTEN BASCULANTE INDUSTRIAL",
            "MOTOR DE INYECCION DE AIRE # 2",
            "MOTOR DE INYECCION DE AIRE # 3",
            "MOTOR DE INYECCION DE AIRE # 4",
            "AMASADOR # 1",
            "FERMENTADOR",
            "SISTEMA DE DETENCION DE INCENDIO",
            "LAMINADORA",
            "ENFRIADOR DE AGUA # 2",
            "FOGON BAJO # 1",
            "FOGON BAJO # 2",
            "FOGON BAJO # 3",
            "LAVAVAJILLAS 1",
            "FILTRO DE CARBON ACTIVADO",
            "ELEVADOR DE CARGA",
            "TABLEROS ELECTRICOS",
            "FUMIGACION",
            "EXTINTORES",
            "PINTURA EXTERNA",
            "PINTURA INTERNA",
            "TABLEROS",
            "LAMPARAS",
            "ESCRITORIOS",
        ],
        "PISO 2": [
            "AIRE ACONDICIONADO 5 TON FAN COIL 4",
            "AIRE ACONDICIONADO 5 TON PISO TECHO 1",
            "AIRE ACONDICIONADO 12000 BTU CUARTO DE IT",
            "ENFRIADOR DE AGUA # 3 (COMPRAS)",
            "A/A 12000 BTU GERENCIA",
            "A/A 12000 BTU SALA DE REUNIONES II",
            "A/A 18000 BTU ADMINISTRACION",
            "EXTINTOR # 1",
            "MICROONDA # 1",
            "ENFRIADOR DE BOTELLON OFICINAS",
            "A/A 18000BTU SALA DE REUNIONES",
            "FILTRO DE CARBON ACTIVADO",
            "ELEVADOR DE CARGA",
            "TABLEROS ELECTRICOS",
            "FUMIGACION",
            "EXTINTORES",
            "PINTURA EXTERNA",
            "PINTURA INTERNA",
            "TABLEROS",
            "LAMPARAS",
            "ESCRITORIOS",
        ],
        "TERRAZA": [
            "MOTOR EXTRACTOR 12000 CFM PLANTA BAJA",
            "MOTOR EXTRACTOR 21000 CFM PISO 1",
            "DUCTOS + TRAMPA GRASAS",
            "TANQUE 1000 LTS # 1",
            "TANQUE 1000 LTS # 2",
            "FILTRO DE CARBON ACTIVADO",
            "ELEVADOR DE CARGA",
            "TABLEROS ELECTRICOS",
            "FUMIGACION",
            "EXTINTORES",
            "PINTURA EXTERNA",
            "PINTURA INTERNA",
            "TABLEROS",
            "LAMPARAS",
            "ESCRITORIOS",
        ],
        "ESTACIONAMIENTO": [
            "CAVA CUARTO DE BASURA",
            "SANTA MARIA # 1 3,5 MTS",
            "SANTA MARIA # 2 3,5 MTS",
            "ENFRIADOR DE AGUA # 4",
            "FILTRO DE CARBON ACTIVADO",
            "ELEVADOR DE CARGA",
            "TABLEROS ELECTRICOS",
            "FUMIGACION",
            "EXTINTORES",
            "PINTURA EXTERNA",
            "PINTURA INTERNA",
            "TABLEROS",
            "LAMPARAS",
            "ESCRITORIOS",
        ],
        "SEMANERO LOS RUICES": [],
    },
    "DEPOSITO": {
        "PB": [
            "A/A 12000 BTU SPLIT // OFICINA PB",
            "CIRCUITO CAMARAS PLANTA BAJA",
            "CIRCUITO CAMARAS PLANTA ALTA",
            "ENFRIADOR SUSHI CAKE",
            "EXTINTORES EVENTOS",
            "EXTINTORES FIJOS NUEVO ESPACIO",
            "MALLAS ANTI RATAS",
            "MICROONDAS # 1",
            "PANTALLAS DE VIDRIO",
            "CREPERAS",
            "EXTRACTORES (6)",
            "HORNO ELECTRICO 110V # 1",
            "HORNO ELECTRICO 110V # 2",
            "PECERAS GRANDES",
            "BOMBONAS DE GAS",
            "ENFRIADOR DE BOTELLON # 1",
            "MAQUINA DE CAFE # 5 LA MARZOCO BLANCA",
            "FILTRO DE CARBON ACTIVADO",
            "ELEVADOR DE CARGA",
            "TABLEROS ELECTRICOS",
            "FUMIGACION",
            "EXTINTORES",
            "PINTURA EXTERNA",
            "PINTURA INTERNA",
            "TABLEROS",
            "LAMPARAS",
            "ESCRITORIOS",
        ],
        "PISO 1": [
            "A/A 12000 BTU VENTANA ///DORMITORIO",
            "A/A 24000 BTU SPLIT 77 OFICINA PA",
            "A/A 8000 BTU VENTANA // DORMITORIO",
            "MICROONDAS # 2",
            "REVERBERO DE MESA",
            "PECERAS PEQUEÑAS",
            "LAMPARAS DE CALOR",
            "ESCALINATAS",
            "HORNO PIZZERO OONI",
            "ENFRIADOR DE BOTELLON # 2",
            "LAVADORA FRIGIDAIRE",
            "SECADORA FRIGIDAIRE",
            "FILTRO DE CARBON ACTIVADO",
            "ELEVADOR DE CARGA",
            "TABLEROS ELECTRICOS",
            "FUMIGACION",
            "EXTINTORES",
            "PINTURA EXTERNA",
            "PINTURA INTERNA",
            "TABLEROS",
            "LAMPARAS",
            "ESCRITORIOS",
        ],
        "NUEVO ESPACIO": [
            "FREIDORA IMPERIAL",
            "FREIDORA STAR BOOK",
            "FREIDORA VULCAN 1",
            "FREIDORA VULCAN 2",
            "FREIDORA DUKER 1",
            "FREIDORA DUKER 2",
            "HORNO ASBER",
            "HORNO UNOX",
            "MAQUINA DE CAFE # 1",
            "MAQUINA DE CAFE # 2",
            "MAQUINA DE CAFE # 3",
            "MOLINO DE CAFE 1",
            "MOLINO DE CAFE 2",
            "PARRILLERAS",
            "PLANCHAS A GAS",
            "REVERBEROS DOBLES",
            "REVERBEROS SENCILLOS",
            "SALAMANDRAS",
            "MAQUINA DE CAFE # 4 BEZZERA",
            "NEVERA EXHIBIDORA",
            "LAVAVAJILLAS # 1 VIEJO",
            "LAVAVAJILLAS # 2 NUEVO",
            "FILTRO DE CARBON ACTIVADO",
            "ELEVADOR DE CARGA",
            "TABLEROS ELECTRICOS",
            "FUMIGACION",
            "EXTINTORES",
            "PINTURA EXTERNA",
            "PINTURA INTERNA",
            "TABLEROS",
            "LAMPARAS",
            "ESCRITORIOS",
            "AIRE ACONDICIONADO 5 TONELADAS ",
        ],
        "TALLER": [
            "MICROONDAS DEL TALLER # 3",
            "ENFRIADOR DE BOTELLON # 3 TALLER",
            "FILTRO DE CARBON ACTIVADO",
            "ELEVADOR DE CARGA",
            "TABLEROS ELECTRICOS",
            "FUMIGACION",
            "EXTINTORES",
            "PINTURA EXTERNA",
            "PINTURA INTERNA",
            "TABLEROS",
            "LAMPARAS",
            "ESCRITORIOS",
        ],
        "ESTACIONAMIENTO": [
            "CHAMBRANAS",
            "MOLINO DE CAFE 3",
            "TANQUES DE AGUA (8000LTS)",
            "TANQUILLAS",
            "FILTRO DE CARBON ACTIVADO",
            "ELEVADOR DE CARGA",
            "TABLEROS ELECTRICOS",
            "FUMIGACION",
            "EXTINTORES",
            "PINTURA EXTERNA",
            "PINTURA INTERNA",
            "TABLEROS",
            "LAMPARAS",
            "ESCRITORIOS",
        ],
        "SEMANERO": [],
    },
    "ALTAMIRA": {
        "OTROS": [
            "ALFOMBRA PISO",
            "EXTINTOR # 2",
            "FILTRO DE CARBON ACTIVADO",
            "ELEVADOR DE CARGA",
            "TABLEROS ELECTRICOS",
            "FUMIGACION",
            "EXTINTORES",
            "PINTURA EXTERNA",
            "PINTURA INTERNA",
            "TABLEROS",
            "LAMPARAS",
            "ESCRITORIOS",
            "LIMPIEZA DE CANALETAS",
            "LIMPIEZA DE TANQUES",
            "LIMPIEZA DE TANQUILLA",
        ],
    },
};

const SEDE_EQUIPOS = {
    "RUICES": [
        "A/A 12000 BTU GERENCIA",
        "A/A 12000 BTU SALA DE REUNIONES II",
        "A/A 18000 BTU ADMINISTRACION",
        "A/A 18000BTU SALA DE REUNIONES",
        "ABATIDOR",
        "AIRE ACONDICIONADO 12000 BTU CUARTO DE IT",
        "AIRE ACONDICIONADO 12000 BTU PANADERIA",
        "AIRE ACONDICIONADO 18000 BTU COMEDOR",
        "AIRE ACONDICIONADO 18000 BTU ENTRADAS",
        "AIRE ACONDICIONADO 5 TON FAN COIL 1",
        "AIRE ACONDICIONADO 5 TON FAN COIL 2",
        "AIRE ACONDICIONADO 5 TON FAN COIL 3",
        "AIRE ACONDICIONADO 5 TON FAN COIL 4",
        "AIRE ACONDICIONADO 5 TON PISO TECHO 1",
        "AMASADOR # 1",
        "ARMARIO REFRIGERADO URSEL 1",
        "ARMARIO REFRIGERADO URSEL 2",
        "BATIDORA KITCHENAID",
        "CAVA CUARTO DE BASURA",
        "CAVA CUARTO DE CONGELACION 1",
        "CAVA CUARTO DE CONGELACION 2",
        "CAVA CUARTO DE CONGELACION 3",
        "CAVA CUARTO DE CONSERVACION 1",
        "CAVA CUARTO DE CONSERVACION 2",
        "COCINA IBOIA # 3",
        "COCINA TURCA # 1",
        "COCINA TURCA # 2",
        "CORTINA DE AIRE 150 CM, 220V",
        "DUCTOS + TRAMPA GRASAS",
        "ELEVADOR DE CARGA",
        "EMPACADORA AL VACIO # 1 VAC MASTER",
        "EMPACADORA AL VACIO # 2 VAMA",
        "ENFRIADOR DE AGUA # 1",
        "ENFRIADOR DE AGUA # 2",
        "ENFRIADOR DE AGUA # 3 (COMPRAS)",
        "ENFRIADOR DE AGUA # 4",
        "ENFRIADOR DE BOTELLON OFICINAS",
        "ESCRITORIOS",
        "EXTINTOR # 1",
        "EXTINTORES",
        "FERMENTADOR",
        "FILTRO DE CARBON ACTIVADO",
        "FILTRO DESBARRADOR",
        "FOGON BAJO # 1",
        "FOGON BAJO # 2",
        "FOGON BAJO # 3",
        "FREIDORA # 1",
        "FREIDORA # 2",
        "FREIDORA # 3",
        "FUMIGACION",
        "HORNO ELECTRICO BALSAM 110 V-PH1 # 1",
        "HORNO ELECTRICO BALSAM 110 V-PH1 # 2",
        "HORNO RATIONAL A GAS 220 V PH2",
        "HORNO RATIONAL TRIFASICO 220V PH3",
        "LAMINADORA",
        "LAMPARAS",
        "LAVAVAJILLAS 1",
        "MESON REFRIGERADO 2 PTA 1 URSEL",
        "MESON REFRIGERADO 2 PTA BALSAM 1 / PANTRY",
        "MESON REFRIGERADO 2 PTA BALSAM 2 / PANTRY",
        "MESON REFRIGERADO 3 PTA 1 URSEL",
        "MESON REFRIGERADO DE GAVETA BALSAM 1 / PRINCIPAL",
        "MESON REFRIGERADO DE GAVETA BALSAM 2 / PRINCIPAL",
        "MESON REFRIGERADO DE GAVETA COMIDA EN FAMILIA",
        "MICROONDA # 1",
        "MOTOR DE INYECCION DE AIRE # 1",
        "MOTOR DE INYECCION DE AIRE # 2",
        "MOTOR DE INYECCION DE AIRE # 3",
        "MOTOR DE INYECCION DE AIRE # 4",
        "MOTOR EXTRACTOR 12000 CFM PLANTA BAJA",
        "MOTOR EXTRACTOR 21000 CFM PISO 1",
        "NEVERA EXHIBIDORA",
        "PELA PAPAS 220 V",
        "PINTURA EXTERNA",
        "PINTURA INTERNA",
        "PLANCHA A GAS",
        "REBANADORA # 1",
        "REBANADORA # 2",
        "REBANADORA # 3 NUEVA",
        "ROBOCOP",
        "SANTA MARIA # 1 3,5 MTS",
        "SANTA MARIA # 2 3,5 MTS",
        "SARTEN BASCULANTE INDUSTRIAL",
        "SISTEMA DE DETENCION DE INCENDIO",
        "SISTEMA HIDRONEUMATICO",
        "TABLEROS",
        "TABLEROS ELECTRICOS",
        "TANQUE 1000 LTS # 1",
        "TANQUE 1000 LTS # 2",
        "TANQUES DE AGUA DE 1000LTS (8 UN)",
        "TOPE FRANCES A GAS 1",
        "TOPE FRANCES A GAS 2",
    ],
    "DEPOSITO": [
        "A/A 12000 BTU SPLIT // OFICINA PB",
        "A/A 12000 BTU VENTANA ///DORMITORIO",
        "A/A 24000 BTU SPLIT 77 OFICINA PA",
        "A/A 8000 BTU VENTANA // DORMITORIO",
        "BOMBONAS DE GAS",
        "CHAMBRANAS",
        "CIRCUITO CAMARAS PLANTA ALTA",
        "CIRCUITO CAMARAS PLANTA BAJA",
        "CREPERAS",
        "ELEVADOR DE CARGA",
        "ENFRIADOR DE BOTELLON # 1",
        "ENFRIADOR DE BOTELLON # 2",
        "ENFRIADOR DE BOTELLON # 3 TALLER",
        "ENFRIADOR SUSHI CAKE",
        "ESCALINATAS",
        "ESCRITORIOS",
        "EXTINTORES",
        "EXTINTORES EVENTOS",
        "EXTINTORES FIJOS NUEVO ESPACIO",
        "EXTRACTORES (6)",
        "FILTRO DE CARBON ACTIVADO",
        "FREIDORA DUKER 1",
        "FREIDORA DUKER 2",
        "FREIDORA IMPERIAL",
        "FREIDORA STAR BOOK",
        "FREIDORA VULCAN 1",
        "FREIDORA VULCAN 2",
        "FUMIGACION",
        "HORNO ASBER",
        "HORNO ELECTRICO 110V # 1",
        "HORNO ELECTRICO 110V # 2",
        "HORNO PIZZERO OONI",
        "HORNO UNOX",
        "LAMPARAS",
        "LAMPARAS DE CALOR",
        "LAVADORA FRIGIDAIRE",
        "LAVAVAJILLAS # 1 VIEJO",
        "LAVAVAJILLAS # 2 NUEVO",
        "MALLAS ANTI RATAS",
        "MAQUINA DE CAFE # 1",
        "MAQUINA DE CAFE # 2",
        "MAQUINA DE CAFE # 3",
        "MAQUINA DE CAFE # 4 BEZZERA",
        "MAQUINA DE CAFE # 5 LA MARZOCO BLANCA",
        "MICROONDAS # 1",
        "MICROONDAS # 2",
        "MICROONDAS DEL TALLER # 3",
        "MOLINO DE CAFE 1",
        "MOLINO DE CAFE 2",
        "MOLINO DE CAFE 3",
        "NEVERA EXHIBIDORA",
        "PANTALLAS DE VIDRIO",
        "PARRILLERAS",
        "PECERAS GRANDES",
        "PECERAS PEQUEÑAS",
        "PINTURA EXTERNA",
        "PINTURA INTERNA",
        "PLANCHAS A GAS",
        "REVERBERO DE MESA",
        "REVERBEROS DOBLES",
        "REVERBEROS SENCILLOS",
        "SALAMANDRAS",
        "SECADORA FRIGIDAIRE",
        "TABLEROS",
        "TABLEROS ELECTRICOS",
        "TANQUES DE AGUA (8000LTS)",
        "TANQUILLAS",
    ],
    "ALTAMIRA": [
        "ALFOMBRA PISO",
        "ELEVADOR DE CARGA",
        "ESCRITORIOS",
        "EXTINTOR # 2",
        "EXTINTORES",
        "FILTRO DE CARBON ACTIVADO",
        "FUMIGACION",
        "LAMPARAS",
        "LIMPIEZA DE CANALETAS",
        "LIMPIEZA DE TANQUES",
        "LIMPIEZA DE TANQUILLA",
        "PINTURA EXTERNA",
        "PINTURA INTERNA",
        "TABLEROS",
        "TABLEROS ELECTRICOS",
    ],
};

const MANTENIMIENTOS = [
    "PREVENTIVO",
    "CORRECTIVO",
    "OTRO",
];


const RUTINA_PREVENTIVO = {
    "Rutina Horno A Gas": [
        "Verificar Entrada de Gas (Regulador y Manguera )", 
        "Lubricar  Perilla Manual de Gas",
        "Lubricar Puertas", 
        "Ajustar Estructura General",
    ],
    "Rutina Horno Electrico": [
        "Verificar Tomas Electricas",
        "Verificar y Ajustar Contactos Electricos (internos)",
        "Verificar Funcionamiento del Motor Ventilador  (Descartas Ruidos, Engrasar de ser necesario)",
        "Validar Funcionamientos de Resistencias",
        "Verificar y Ajustar Puertas",
        "Ajustar Estructura General"
        
    ],
    "Rutina Horno Mixto":[
        "Verificar Tomas Electricas",
        "Verificar y Ajustar Contactos Electricos (internos)",
        "Verificar Funcionamiento del Motor Ventilador  (Descartas Ruidos, Engrasar de ser necesario)",
        "Validar Funcionamientos de Resistencias",
        "Verificar y Ajustar Puertas",
        "Ajustar Estructura General",
        "Verificar Entrada de Gas (Descarte de Fugas)",
        "Lubricar Valbulas del Equipo"
    ],
    "Rutina Cava Cuarto/Nevera": [
        "Limpieza con Agua a Presion el Condensador ",
        "Limpieza con Agua a Presion el Evaporador",
        "Mantenimiento de Motores del Condesador ",
        "Mantenimiento de Motores del Evaporador",
        "Verificar Estado de Aislantes Termicos",
        "Ajustes de Puertas",
        "Chequear Cortinas de PVC",
        { label: "Chequeo de Presiones", expand: [
            { label: "P1 (PSI)", type: "number", min: 0, max: 20 },
            { label: "P2 (PSI)", type: "number", min: 0, max: 20 },
        ] },
        {label: "Chequeo de Consumo Electrico", type:"toggle", expand:[
            {label:"L1 (AMP)", type:"number"}, 
            {label:"L2 (AMP)", type:"number"}, 
            {label:"L3 (AMP)", type:"number"}]},
        "Ajuste de Terminales Electricos",
        "Limpieza de Tablero",
        {label:"Limpieza de Bandeja del Evaporador", type:"toggle", expand:[{label:"Realizada", type:"toggle"}]},
        "Chequear Resistencias Electricas"
        
    ],
    "Rutina Peceras": [
        "Chequeo de Papel Translucido (Esta en buen estado si/no)",
        "Verificar que el Vidrio de la Pecera Este en buen Estado",
        "Verificar que no Filtre Agua Por las Uniones de la Pecera",        
    ],
    "Rutina Maquinas de Cafe": [
        "Chequeo de Componentes Electricos",
        "Chequear que la Caldera no Presente Fugas de Agua",
        "Chequear Valvula de Seguridad",
        "Limpieza de los Grupos Dispensadores de Cafe (con producto )",
        "Chequear Manometros de la Valvula de Presion",
        "Limpieza de Porta Filtros (con producto)",
        "Ajustes de Estructura General (Tapas, Patas,Regillas, Magueras, etc)",
        "Limpieza de Boquillas de las Lancetas",
        "Limpieza de Bandeja de Agua",
    ],
    "Rutina Molinos de Cafe": [
        "Chequeo de Componentes Electricos",
        "Limpieza de Cavesales",
        "Verificar Ruidos Extraños en el Motor (Engrasar de ser necesario o remplazar)",
        "Verificar Estado de las Muelas del Molino",
        "Verificar Estado de las Tolvas y Estructura General (Ajustar de ser necesario)",
    ],
    "Rutina Santa Maria": [
        "Limpieza General del Equipo",
        "Lubricacion de Rieles (Formula marina)",
        "Limpieza de Tambor y Fleje (con desengrasante y Agua a Presion)",
        "Lubricaion de Fleje (Formula Marina)",
        "Cheque de Componentes Electricos"
    ],
    "Rutina Escalinatas": [
        "Chequeo de Estado de la Pintura (Pintar de ser necesario)",
        "Verificar Estado de la Madera (Ver que no este dañada o podrida)",
    ],
    "Rutina Reberberos": [
        "Verificar Entrada de Gas (Regulador y Manguera )",
        "Verificar que no Haya Fugas de Gas",
        "Verificar Calidad de la Llama (Graduar entrada de aire de ser necesario)",
        "Lubricar Valvulas ",
        "Verificar Estado de la Estructura General (Pintar de ser necesario)"
    ],
    "Rutina Lamparas de Calor": [
        "Verificar conexiones Electricas",
        "Ajustes de Socates y Bombillos (cambiar de ser necesario)",
        "Verificar Estado de la Estructura General (Pintar de ser necesario)",
    
    ],
    "Rutina Cocinas": [
        "Mantenimiento de Valvulas (lubricacion)",
        " Limpieza de Pilotos y Quemadores",
        "Ajustes de Termo pilas o Termo Cuplas",
        "Verificar Tuercas y Conexciones de Entrada de Gas (Buscar Fugas)",
        "Verificar Entrada de Aire (Ajustar de ser necesario)",

    ],
    "Rutina Lava Vajillas": [
        "Verificar Conexiones Electricas",
        "Verificar quimicos de Limpieza (Secante y Detergente)",
        "Desincrustar el Equipo (con producto desincrustante)",
        "Limpieza externa ",

    ],
    "Rutina Molino de Carne": [
        "Ajustar partes moviles",
        "Chequear componentes electricos",
        "verificar rodamiento de motor (Lubricar de ser necesario)",
        "Lubricar cadena"
    ],
    "Rutina Laminadora": [
        "Chequear componentes electricos",
        "Verificar estado de bandas y rodillos",
        "Limpieza interna con aire a presion"
    ],
    "Rutina Amasadora": [
        "Verificar componentes electricos",
        "Chequar Tension de correa (cambiar de ser necesario)",
        "Chequeo de Motor (Descartar ruidos extraños)"
    ],
    "Rutina Planchas Electricas": [
        "Chequeo de componentes electricos",
        "Ajustes de estructura general",
        "Verificar que trabajen las resistencia"
    ],
    "Rutina Enfriadores de Agua": [
        "Revision de componentes electricos",
        "Ajustes de estrutura",
        "Limpieza de valvulas dispensadoras de agua (cambiar de ser necesario)",
        
    ],
    "Rutina Motores de Inyeccion ": [
        "Cheqqueo de correa (cambiar de ser necesario",
        "Limpieza de aspas ",
        "Limpieza de rejillas ",
        "Chequeo y ajustes de componentes electricos",
        "Chequear motor electrico (ruidos extraños en rodamiento)"
    ],
    "Rutina Motores de Extracion": [
        "Chequeo y ajuste de correa",
        "Lubricar rodamientos",
        "Chequeo de motor electrico",
        "Ajustar sistema de amortiguacion ",
        "Chequo y ajustes de componentes electricos",
        "Chequeo de Rodamiento de turbina"
    ],
    "Rutina Freidora": [
        "Chequeo de llama de piloto (destapar de ser necesario)",
        "Chequeo de encendido",
        "Limpieza de quemadores ",
        "limpieza de regulador de gas",
        "Chequeo de fuga de gas",
        "Ajuste general de estructura"
    ],
    "Rutina Aires Acondicionados": [
        "Limpieza con Agua a Presion el Condensador ",
        "Limpieza con Agua a Presion el Evaporador",
        "Mantenimiento de Motores del Condesador ",
        "Mantenimiento de Motores del Evaporador",
        "Verificar Estado de Aislantes Termicos",
        { label: "Chequeo de Presiones", expand: [
            { label: "P1 (PSI)", type: "number"},
            { label: "P2 (PSI)", type: "number"}
        ] },
        {label: "Chequeo de Consumo Electrico", type:"toggle", expand:[
            {label:"L1 (AMP)", type:"number"}, 
            {label:"L2 (AMP)", type:"number"}, 
            {label:"L3 (AMP)", type:"number"}]},
        "Ajuste de Terminales Electricos",
        "Limpieza de Tarjeta",
        "Limpieza de Bandeja del Evaporador"
    ],

    "Rutina Hidroneumatico": [
        "Chequeo de bomba ",
        "Limpieza de tanque",
        "Chequeo de valvula",
        "Chequeo de flotante"
    ],
    "Rutina Tablero Electrico": [
        "Chequeo y ajustes de componentes electricos",
        "Limpieza Interna de tablero"
    ],
    "Rutina Empacadoras al Vacio": [
        "Cambio de Aceite",
        "Chequeo y ajustes de componentes electricos",
        "Limpieza y lubricacion de pistones neumaticos",
        "Chequeo de cinta teflon (cambiar de ser necesario)",
        "Chequeo de estado de sello compuerta (Cambiar de ser necesario)",
        "Limpieza de barras de sellado"
    ],
    "Rutina Sarten Basculante ": [],
    "Rutina Luminarias": [
        "Chequeo de tubos oo bombillas",
        "Chequeo de componentes Electricos (socates)",
        "Limpieza externa de carcasa y acrilico"

    ],
    "Rutina Seguridad":[
        "Chequeo de fecha de vencimiento Extintores",
        "Chequeo de cerco electrico",
        "chequeo de sistema de deteccion de incendios"
    ],
    "Rutina Chambrana": [
        "Revisión de reguetones",
        "Rebicion de patas (revicion de soldadura )",
        "Revicion de estado de pintura"
    ]
    
};

const RUTINA_CORRECTIVO = {
    "Rutina Correctiva": [
        "Plomeria",
        "Soldadura",
        "Electricidad",
        "Refigeracion",
        "Carpinteria",
        "Pintura",
        "Albanileria",
        "Otros"
    ]
};

const RUTINA_TALLER = {
    "Actividades de Semaneros": [
        {
            label: "Tanques",
            type: "toggle",
            expand: [
                { label: "Llenos", type: "number" },
                { label: "Vacios", type: "number", min: 0, max: 20 },
                { label: "Entrada de Agua de la Calle", type: "toggle" },
                { label: "Solicitar cisterna", type: "toggle" }
            ]
        },
        {
            label: "Bombonas",
            type: "toggle",
            expand: [
                { label: "Llenas", type: "number" },
                { label: "Vacias", type: "number" },
                { label: "Medias", type: "number" }
            ]
        },
        {
            label : "Aceites", type : "toggle",
            expand:[
                {label:"Quemados", type: "number"},
                {label:"Buenos", type: "number"},
                {label:"Vender", type: "toggle", 
                    expand:[ 
                        {label:"Cuanto", type: "number"},
                        {label: "N° de Factura", type: "Text"}
                    ]
                }
            ]
        }
    ]
};

const RUTINA_SEMANARIO_RUICES = [
    {
        titulo: "Planta baja",
        campos: [
            { label: "Cava cuarto #1", type: "number" },
            { label: "Cava cuarto #2", type: "number" },
            { label: "Cava cuarto #3", type: "number" },
            { label: "Armario de pasapalos", type: "number" },
            { label: "Armario To Go", type: "number" },
            { label: "Armario refrigerado", type: "number" },
            { label: "Mesón refrigerado", type: "number" },
            { label: "Aire acondicionado", type: "select", options: ["Encendido", "Apagado"] },
            { label: "Extracción", type: "select", options: ["Encendido", "Apagado"] },
            { label: "Inyección", type: "select", options: ["Encendido", "Apagado"] },
            { label: "Llave de gas", type: "select", options: ["Abierta", "Cerrada"] },
            { label: "Tanques en reserva", type: "number" },
            { label: "Tanques en uso", type: "number" },
            { label: "Bomba de agua", type: "select", options: ["Automático", "Manual", "Apagada"] },
            { label: "Agua de la calle", type: "select", options: ["Si", "No"] },
            { label: "Horno Rational a gas", type: "select", options: ["Encendido", "Apagado"] }
        ]
    },
    {
        titulo: "Piso 1",
        campos: [
            { label: "Llave de gas", type: "select", options: ["Abierta", "Cerrada"] },
            { label: "Armario refrigerado", type: "number" },
            { label: "Mesón refrigerado E", type: "number" },
            { label: "Mesón refrigerado F", type: "number" },
            { label: "Horno Rational", type: "select", options: ["Encendido", "Apagado"] },
            { label: "Abatidor", type: "select", options: ["Encendido", "Apagado"] },
            { label: "Aires de sala", type: "select", options: ["Encendido", "Apagado"] },
            { label: "Aire party / pantry", type: "select", options: ["Encendido", "Apagado"] },
            { label: "Aire de panadería", type: "select", options: ["Encendido", "Apagado"] },
            { label: "Inyección", type: "select", options: ["Encendido", "Apagado"] },
            { label: "Ascensor", type: "select", options: ["Sin novedad", "Con novedad", "Fuera de servicio"] }
        ]
    },
    {
        titulo: "Estacionamiento",
        campos: [
            { label: "Santa María", type: "select", options: ["Abierta", "Cerrada"] },
            { label: "Reflectores", type: "select", options: ["Encendido", "Apagado"] },
            { label: "Cerco eléctrico", type: "select", options: ["Encendido", "Apagado"] }
        ]
    },
    {
        titulo: "Terraza",
        campos: [
            { label: "Tanque de agua", type: "select", options: ["En servicio", "Fuera de servicio"] },
            { label: "Aires acondicionados", type: "select", options: ["Encendido", "Apagado"] },
            { label: "Reflectores", type: "select", options: ["Encendido", "Apagado"] },
            { label: "Extractor 12000 CFM", type: "select", options: ["Encendido", "Apagado"] },
            { label: "Extractor 21000 CFM", type: "select", options: ["Encendido", "Apagado"] }
        ]
    },
    {
        titulo: "Tanques",
        tareas: [
            {
                label: "Tanques",
                type: "toggle",
                expand: [
                    { label: "Llenos", type: "number" },
                    { label: "Vacios", type: "number", min: 0, max: 20 },
                    { label: "Entrada de Agua de la Calle", type: "toggle" },
                    { label: "Solicitar cisterna", type: "toggle" }
                ]
            }
        ]
    }
];

const EQUIPO_RUTINA = {
    "A/A 12000 BTU GERENCIA": "Rutina Aires Acondicionados",
    "A/A 12000 BTU SALA DE REUNIONES II": "Rutina Aires Acondicionados",
    "A/A 12000 BTU SPLIT // OFICINA PB": "Rutina Aires Acondicionados",
    "A/A 12000 BTU VENTANA ///DORMITORIO": "Rutina Aires Acondicionados",
    "A/A 18000 BTU ADMINISTRACION": "Rutina Aires Acondicionados",
    "A/A 18000BTU SALA DE REUNIONES": "Rutina Aires Acondicionados",
    "A/A 24000 BTU SPLIT 77 OFICINA PA": "Rutina Aires Acondicionados",
    "A/A 8000 BTU VENTANA // DORMITORIO": "Rutina Aires Acondicionados",
    "ABATIDOR": "Rutina Cava Cuarto/Nevera",
    "AIRE ACONDICIONADO 12000 BTU CUARTO DE IT": "Rutina Aires Acondicionados",
    "AIRE ACONDICIONADO 12000 BTU PANADERIA": "Rutina Aires Acondicionados",
    "AIRE ACONDICIONADO 18000 BTU COMEDOR": "Rutina Aires Acondicionados",
    "AIRE ACONDICIONADO 18000 BTU ENTRADAS": "Rutina Aires Acondicionados",
    "AIRE ACONDICIONADO 5 TON FAN COIL 1": "Rutina Aires Acondicionados",
    "AIRE ACONDICIONADO 5 TON FAN COIL 2": "Rutina Aires Acondicionados",
    "AIRE ACONDICIONADO 5 TON FAN COIL 3": "Rutina Aires Acondicionados",
    "AIRE ACONDICIONADO 5 TON FAN COIL 4": "Rutina Aires Acondicionados",
    "AIRE ACONDICIONADO 5 TON PISO TECHO 1": "Rutina Aires Acondicionados",
    "AIRE ACONDICIONADO 5 TONELADAS ": "Rutina Aires Acondicionados",
    "ALFOMBRA PISO": "Rutina Area Comun",
    "AMASADOR # 1": "Rutina Amasadora",
    "ARMARIO REFRIGERADO URSEL 1": "Rutina Cava Cuarto/Nevera",
    "ARMARIO REFRIGERADO URSEL 2": "Rutina Cava Cuarto/Nevera",
    "BOMBONAS DE GAS": "Rutina Cocina",
    "CAVA CUARTO DE BASURA": "Rutina Cava Cuarto/Nevera",
    "CAVA CUARTO DE CONGELACION 1": "Rutina Cava Cuarto/Nevera",
    "CAVA CUARTO DE CONGELACION 2": "Rutina Cava Cuarto/Nevera",
    "CAVA CUARTO DE CONGELACION 3": "Rutina Cava Cuarto/Nevera",
    "CAVA CUARTO DE CONSERVACION 1": "Rutina Cava Cuarto/Nevera",
    "CAVA CUARTO DE CONSERVACION 2": "Rutina Cava Cuarto/Nevera",
    "CHAMBRANAS": "Rutina Chambrana",
    "CIRCUITO CAMARAS PLANTA ALTA": "Rutina Area Comun",
    "CIRCUITO CAMARAS PLANTA BAJA": "Rutina Area Comun",
    "COCINA IBOIA # 3": "Rutina Cocinas",
    "COCINA TURCA # 1": "Rutina Cocinas",
    "COCINA TURCA # 2": "Rutina Cocinas",
    "CORTINA DE AIRE 150 CM, 220V": "Rutina Area Comun",
    "CREPERAS": "Rutina Cocina",
    "DUCTOS + TRAMPA GRASAS": "",
    "ELEVADOR DE CARGA": "Rutina Area Comun",
    "EMPACADORA AL VACIO # 1 VAC MASTER": "Rutina Empacadoras al Vacio",
    "EMPACADORA AL VACIO # 2 VAMA": "Rutina Empacadoras al Vacio",
    "ENFRIADOR DE AGUA # 1": "Rutina Enfriadores de Agua",
    "ENFRIADOR DE AGUA # 2": "Rutina Enfriadores de Agua",
    "ENFRIADOR DE AGUA # 3 (COMPRAS)": "Rutina Enfriadores de Agua",
    "ENFRIADOR DE AGUA # 4": "Rutina Enfriadores de Agua",
    "ENFRIADOR DE BOTELLON # 1": "Rutina Enfriadores de Agua",
    "ENFRIADOR DE BOTELLON # 2": "Rutina Enfriadores de Agua",
    "ENFRIADOR DE BOTELLON # 3 TALLER": "Rutina Enfriadores de Agua",
    "ENFRIADOR DE BOTELLON OFICINAS": "Rutina Enfriadores de Agua",
    "ENFRIADOR SUSHI CAKE": "Rutina Cava Cuarto/Nevera",
    "ESCALINATAS": "Rutina Escalinatas",
    "EXTINTOR # 1": "Rutina Seguridad",
    "EXTINTOR # 2": "Rutina Seguridad",
    "EXTINTORES": "Rutina Seguridad",
    "EXTINTORES EVENTOS": "Rutina Seguridad",
    "EXTINTORES FIJOS NUEVO ESPACIO": "Rutina Seguridad",
    "EXTRACTORES (6)": "Rutina Cocina",
    "FERMENTADOR": "Rutina Cocina",
    "FILTRO DE CARBON ACTIVADO": "...",
    "FILTRO DESBARRADOR": "...",
    "FOGON BAJO # 1": "Rutina Cocinas",
    "FOGON BAJO # 2": "Rutina Cocinas",
    "FOGON BAJO # 3": "Rutina Cocinas",
    "FREIDORA # 1": "Rutina Freidora",
    "FREIDORA # 2": "Rutina Freidora",
    "FREIDORA # 3": "Rutina Freidora",
    "FREIDORA DUKER 1": "Rutina Freidora",
    "FREIDORA DUKER 2": "Rutina Freidora",
    "FREIDORA IMPERIAL": "Rutina Freidora",
    "FREIDORA STAR BOOK": "Rutina Freidora",
    "FREIDORA VULCAN 1": "Rutina Freidora",
    "FREIDORA VULCAN 2": "Rutina Freidora",
    "FUMIGACION": "Rutina Seguridad",
    "HORNO ASBER": "Rutina Horno A Gas",
    "HORNO ELECTRICO 110V # 1": "Rutina Horno Electrico",
    "HORNO ELECTRICO 110V # 2": "Rutina Horno Electrico",
    "HORNO ELECTRICO BALSAM 110 V-PH1 # 1": "Rutina Horno Mixto",
    "HORNO ELECTRICO BALSAM 110 V-PH1 # 2": "Rutina Horno Mixto",
    "HORNO PIZZERO OONI": "Rutina Horno A Gas",
    "HORNO RATIONAL A GAS 220 V PH2": "Rutina Horno Mixto",
    "HORNO RATIONAL TRIFASICO 220V PH3": "Rutina Horno Electrico",
    "HORNO UNOX": "Rutina Horno Electrico",
    "LAMINADORA": "Rutina Laminadora",
    "LAMPARAS": "Rutina Luminarias",
    "LAMPARAS DE CALOR": "Rutina Lamparas de Calor",
    "LAVAVAJILLAS # 1 VIEJO": "Rutina Lava Vajillas",
    "LAVAVAJILLAS # 2 NUEVO": "Rutina Lava Vajillas",
    "LAVAVAJILLAS 1": "Rutina Lava Vajillas",
    "LIMPIEZA DE CANALETAS": "",
    "LIMPIEZA DE TANQUES": "Rutina Hidroneumatico",
    "LIMPIEZA DE TANQUILLA": "Rutina Almacen",
    "MALLAS ANTI RATAS": "Rutina Seguridad",
    "MAQUINA DE CAFE # 1": "Rutina Maquinas de Cafe",
    "MAQUINA DE CAFE # 2": "Rutina Maquinas de Cafe",
    "MAQUINA DE CAFE # 3": "Rutina Maquinas de Cafe",
    "MAQUINA DE CAFE # 4 BEZZERA": "Rutina Maquinas de Cafe",
    "MAQUINA DE CAFE # 5 LA MARZOCO BLANCA": "Rutina Maquinas de Cafe",
    "MESON REFRIGERADO 2 PTA 1 URSEL": "Rutina Almacen",
    "MESON REFRIGERADO 2 PTA BALSAM 1 / PANTRY": "Rutina Almacen",
    "MESON REFRIGERADO 2 PTA BALSAM 2 / PANTRY": "Rutina Almacen",
    "MESON REFRIGERADO 3 PTA 1 URSEL": "Rutina Almacen",
    "MESON REFRIGERADO DE GAVETA BALSAM 1 / PRINCIPAL": "Rutina Almacen",
    "MESON REFRIGERADO DE GAVETA BALSAM 2 / PRINCIPAL": "Rutina Almacen",
    "MESON REFRIGERADO DE GAVETA COMIDA EN FAMILIA": "Rutina Almacen",
    "MICROONDA # 1": "Rutina Cocina",
    "MICROONDAS # 1": "Rutina Cocina",
    "MICROONDAS # 2": "Rutina Cocina",
    "MICROONDAS DEL TALLER # 3": "Rutina Cocina",
    "MOLINO DE CAFE 1": "Rutina Molinos de Cafe",
    "MOLINO DE CAFE 2": "Rutina Molinos de Cafe",
    "MOLINO DE CAFE 3": "Rutina Molinos de Cafe",
    "MOTOR DE INYECCION DE AIRE # 1": "Rutina Motores de Inyeccion ",
    "MOTOR DE INYECCION DE AIRE # 2": "Rutina Motores de Inyeccion ",
    "MOTOR DE INYECCION DE AIRE # 3": "Rutina Motores de Inyeccion ",
    "MOTOR DE INYECCION DE AIRE # 4": "Rutina Motores de Inyeccion ",
    "MOTOR EXTRACTOR 12000 CFM PLANTA BAJA": "Rutina Motores de Extracion",
    "MOTOR EXTRACTOR 21000 CFM PISO 1": "Rutina Motores de Extracion",
    "NEVERA EXHIBIDORA": "Rutina Cava Cuarto/Nevera",
    "PARRILLERAS": "Rutina Cocina",
    "PECERAS GRANDES": "Rutina Peceras",
    "PECERAS PEQUEÑAS": "Rutina Peceras",
    "PELA PAPAS 220 V": "Rutina Cocina",
    "PLANCHA A GAS": "Rutina Reberberos",
    "PLANCHAS A GAS": "Rutina Reberberos",
    "REBANADORA # 1": "Rutina Cocina",
    "REBANADORA # 2": "Rutina Cocina",
    "REBANADORA # 3 NUEVA": "Rutina Cocina",
    "REVERBERO DE MESA": "Rutina Reberberos",
    "REVERBEROS DOBLES": "Rutina Reberberos",
    "REVERBEROS SENCILLOS": "Rutina Reberberos",
    "ROBOCOP": "Rutina Cocina",
    "SALAMANDRAS": "Rutina Horno A Gas",
    "SANTA MARIA # 1 3,5 MTS": "Rutina Santa Maria",
    "SANTA MARIA # 2 3,5 MTS": "Rutina Santa Maria",
    "SARTEN BASCULANTE INDUSTRIAL": "Rutina Cocina",
    "SISTEMA DE DETENCION DE INCENDIO": "Rutina de Seguridad",
    "SISTEMA HIDRONEUMATICO": "Rutina Hidroneumatico",
    "TABLEROS": "Rutina Tablero Electrico",
    "TABLEROS ELECTRICOS": "Rutina Tablero Electrico",
    "TANQUE 1000 LTS # 1": "Rutina Hidroneumatico",
    "TANQUE 1000 LTS # 2": "Rutina Hidroneumatico",
    "TANQUES DE AGUA (8000LTS)": "Rutina Hidroneumatico",
    "TANQUES DE AGUA DE 1000LTS (8 UN)": "Rutina Hidroneumatico",
    "TANQUILLAS": "Rutina Tanquilla",
    "TOPE FRANCES A GAS 1": "Rutina Cocinas",
    "TOPE FRANCES A GAS 2": "Rutina Cocinas",
};

const APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbzXNLVbmo8H8U6kdo0ffFSJo_6xur9Mdfs0ho6nAGQFKqOBLzAIRgROzURdjzamA3XIUw/exec";
